In [21]:
class baseClass:
	def __init__(self):
		self.l=[]
		self.l.append(0)
class derivedClass(baseClass):
	def __init__(self):
		super().__init__()


a=baseClass()
b=derivedClass()
c=derivedClass()

a.l.append(1)
b.l.append(2)
c.l.append(3)
print(a.l)
print(b.l)
print(c.l)


[0, 1]
[0, 2]
[0, 3]


In [2]:
import numpy as np
from sklearn.model_selection import StratifiedKFold

# 构造数据
X = np.arange(10).reshape((10, 1))
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

print(f"X={X}")
print(f"y={y}")

# 定义分层K折
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# 打印每一折的训练集和测试集数据
for fold, (train_idx, test_idx) in enumerate(skf.split(X, y)):
	print(f"\nFold {fold+1}")
	print("Train X:\n", X[train_idx])
	print("Train y:\n", y[train_idx])
	print("Test X:\n", X[test_idx])
	print("Test y:\n", y[test_idx])


X=[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y=[0 0 0 0 1 1 1 1 1 1]

Fold 1
Train X:
 [[1]
 [3]
 [4]
 [6]
 [8]
 [9]]
Train y:
 [0 0 1 1 1 1]
Test X:
 [[0]
 [2]
 [5]
 [7]]
Test y:
 [0 0 1 1]

Fold 2
Train X:
 [[0]
 [1]
 [2]
 [5]
 [6]
 [7]
 [8]]
Train y:
 [0 0 0 1 1 1 1]
Test X:
 [[3]
 [4]
 [9]]
Test y:
 [0 1 1]

Fold 3
Train X:
 [[0]
 [2]
 [3]
 [4]
 [5]
 [7]
 [9]]
Train y:
 [0 0 0 1 1 1 1]
Test X:
 [[1]
 [6]
 [8]]
Test y:
 [0 1 1]
